

@/home/student/Data/cit225/oracle/salon/cleanup_oracle.sql;
@/home/student/Data/cit225/oracle/salon/create_salon.sql;
@/home/student/Data/cit225/oracle/salon/salon_insert.sql;


-- Show the Name, Type and Price of items (products and services) purchased by each customer sorted by customer lastname
SELECT t1.name AS CUSTOMER_NAME, t4.name AS "PRODUCT/SERVICE", t4.type, t4.price
    FROM customer t1 JOIN tran t2
        ON t1.customer_id = t2.customer_id
    JOIN tran_detail t3
        ON t2.tran_id = t3.tran_id
    JOIN product t4
        ON t3.product_id = t4.product_id
    ORDER BY t1.name;

-- Show the total spend of each customer sorted by spend descending
SELECT UNIQUE t1.name AS CUSTOMER_NAME, SUM(t4.price) AS TOTAL
    FROM customer t1 JOIN tran t2
        ON t1.customer_id = t2.customer_id
    JOIN tran_detail t3
        ON t2.tran_id = t3.tran_id
    JOIN product t4
        ON t3.product_id = t4.product_id
    GROUP BY t1.name
    ORDER BY TOTAL DESC;


-- Show the total revenue generated by each employee sorted by revenue descending
SELECT t1.name AS EMPLOYEE, SUM(t3.amount_charged) AS REVENUE
    FROM employee t1 JOIN tran t2
        ON t1.employee_id = t2.employee_id
    JOIN tran_detail t3
        ON t2.tran_id = t3.tran_id
    JOIN product t4
        ON t3.product_id = t4.product_id
    GROUP BY t1.name
    ORDER BY REVENUE DESC;


-- Show each employee with their title, hire date, manager and manager title
SELECT t1.name, t1.title, t1.hire_date, t2.name AS BOSS, t2.title AS "BOSS POSITION"
    FROM employee t1 JOIN employee t2
        ON t1.manager_id = t2.employee_id OR t1.manager_id IS NULL;
    
   
   
-- Unnormalized Data

